#!/bin/bash
export CLAUDE_CONFIG_DIR="./claude-config"
mkdir -p "$CLAUDE_CONFIG_DIR"
claude --dangerously-skip-permissions --dangerously-load-development-channels --channels "plugin:discord@parnmanas" "$@"
